// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfaPuMMqzyOWgiQqlWd2kWMHEMz_4J318',
    appId: '1:28360554409:web:68008f3e1647696c8af6b8',
    messagingSenderId: '28360554409',
    projectId: 'wwmm-5063a',
    authDomain: 'wwmm-5063a.firebaseapp.com',
    storageBucket: 'wwmm-5063a.appspot.com',
    measurementId: 'G-6YB28RD4TR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSP96mdRBhPWEfjRPb8Uv7AfUe0sSh9B4',
    appId: '1:28360554409:android:3c8b5e050a3af6338af6b8',
    messagingSenderId: '28360554409',
    projectId: 'wwmm-5063a',
    storageBucket: 'wwmm-5063a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzWSA5D5PWAcWYjlFaR6SjuuHMror1eYg',
    appId: '1:28360554409:ios:86a78ec58d1083118af6b8',
    messagingSenderId: '28360554409',
    projectId: 'wwmm-5063a',
    storageBucket: 'wwmm-5063a.appspot.com',
    iosClientId: '28360554409-gtrf7773vrmvudo760i20obkuv9v8hqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseWwmm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzWSA5D5PWAcWYjlFaR6SjuuHMror1eYg',
    appId: '1:28360554409:ios:c54077315bbd95048af6b8',
    messagingSenderId: '28360554409',
    projectId: 'wwmm-5063a',
    storageBucket: 'wwmm-5063a.appspot.com',
    iosClientId: '28360554409-euoiidvbqg1u73f157u6sfk4k0k879rr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseWwmm.RunnerTests',
  );
}
